// @ts-expect-error Generated by the OpenNext build.
import nextHandler from "../.open-next/worker.js";
import { withDatabaseScope, withDatabaseResponse } from "../src/db/scope";
import { claimNextJob, runClaimedJob } from "../src/jobs/runner";
import { ensurePilotScanSchedules } from "../src/jobs/pilotSchedule";
import { enqueueOnce } from "../src/jobs/enqueue";

import { withAiBinding, type AiBinding } from "../src/lib/cloudflareAi";

interface Env { SCANS_ENABLED?: string; AI?: AiBinding }

const worker = {
  fetch(request: Request, env: Env, ctx: { waitUntil(promise: Promise<unknown>): void }) {
    return withAiBinding(env.AI, () => withDatabaseResponse(() => nextHandler.fetch(request, env, ctx)));
  },
  async scheduled(_event: unknown, env: Env) {
    if (env.SCANS_ENABLED !== "true") return;
    // One job per tick; PostgreSQL leases prevent concurrent ticks claiming it twice.
    // Await all work: request waitUntil's short lifetime is unsuitable for scans.
    await withAiBinding(env.AI, () => withDatabaseScope(async () => {
      const now = new Date();
      await ensurePilotScanSchedules(now);
      if (now.getUTCMinutes() < 5) await enqueueOnce("digest");
      if (now.getUTCHours() === 0 && now.getUTCMinutes() < 5) await enqueueOnce("retention");
      const job = await claimNextJob(new Date());
      if (job) await runClaimedJob(job);
    }));
  },
};
export default worker;
